
NAME: ''
OUTPUT_DIR: './output/GANDFCL/cifar10/ResNet32/Base0/task5/seed-0/LwF-loss/test2'
SHOW_STEP: 50
SAVE_STEP: 100
VALID_STEP: 25
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'
CPU_MODE: False
use_best_model: False
task1_MODEL: "/home/likunchi/reuse-model/cifar10-base0-task5-base_latest_model.pth"
pretrained_MODEL: ""
use_base_half: False
checkpoints: ''
save_model: False
use_Contra_train_transform: False
train_first_task: False

seed: 0
trainer_name: "GAN_gen"
# ----- DATASET BUILDER -----

DATASET:
  dataset: "Torchvision_Datasets_Split"
  dataset_name: "CIFAR10"                  #mnist, mnist28, CIFAR10, CIFAR100, imagenet, svhn
#  data_root: "/data0/user/kcli/Datasets"
  data_root: "/home/likunchi/Datasets"
  all_classes: 10
  all_tasks: 5
  split_seed: 0
  val_length: 0
# ----- resume -----

RESUME:
  use_resume: False
  resumed_model_path: ""

# ----- pre-train setting -----
PRETRAINED:
  use_pretrained_model: False
  MODEL: ""


# ----- extractor BUILDER -----
extractor:
#  TYPE: 'resnet18'
  #TYPE: "resnet34"
  TYPE: "res32_cifar"
  rate: 1.
  output_feature_dim: 64
#  output_feature_dim: 512


#----- model -----
model:
  loss_type: "LwF"
#  loss_type: "ABD"
  kd_lambda: 1e-1
  T: 2.
  TRAIN:
    BATCH_SIZE: 128
#    MAX_EPOCH: 340
    MAX_EPOCH: 170
    NUM_WORKERS: 4
    SHUFFLE: True
    OPTIMIZER:
      TYPE: 'SGD'
      BASE_LR: 0.1
      MOMENTUM: 0.9
      WEIGHT_DECAY: 2e-4
    LR_SCHEDULER:
#      TYPE: 'multistep'
      TYPE: 'warmup'
#      LR_STEP: [120, 200, 260, 300]
      LR_STEP: [60, 100, 130, 150]
      LR_FACTOR: 0.1
      WARM_EPOCH: 5

generator:
  gen_model_name: "CIFAR_GAN"
  generator_epochs: 100
  generator_lr: 0.0002
  latent_size: 64
  TRAIN:
    BATCH_SIZE: 64
    NUM_WORKERS: 4
discriminator:
  dis_model_name: "CIFAR_DIS"
  discriminator_lr: 0.0002



