
NAME: ''

OUTPUT_DIR: './output/ERA-EFCL/visualize/ERA-EFCL/cifar10/ResNet32/task2/test1'
SHOW_STEP: 50
SAVE_STEP: 100
VALID_STEP: 25
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'
CPU_MODE: False
#task1_MODEL: "/home/likunchi/CL_research/DataFreeCL/output/foster_DFCL/cifar10/ResNet32/Base0/task2/test1/models/base_latest_model.pth"
#fctm_model_path: "/home/likunchi/CL_research/DataFreeCL/output/foster_DFCL/cifar10/ResNet32/Base0/task2/test1/models/latest_FCTM.pth"

#task1_MODEL: "/home/likunchi/CL_research/DataFreeCL-V2/output/CKDF_ERA/cifar10/ResNet32/Base0/task2/test1/models/base_latest_model.pth"
#fctm_model_path: "/home/likunchi/CL_research/DataFreeCL-V2/output/CKDF_ERA/cifar10/ResNet32/Base0/task2/test1/models/latest_FCN.pth"

task1_MODEL: "/home/likunchi/CL_research/DataFreeCL/output/ERA-RDFCL/cifar10/ResNet32/Base0/task2/seed-0/test1/models/base_latest_model.pth"
fctm_model_path: "/home/likunchi/CL_research/DataFreeCL/output/ERA-RDFCL/cifar10/ResNet32/Base0/task2/seed-0/test1/models/latest_FCTM.pth"
seed: 0

# ----- DATASET BUILDER -----

DATASET:
  dataset: "Torchvision_Datasets_Split"
  dataset_name: "CIFAR10"                  #mnist, mnist28, CIFAR10, CIFAR100, imagenet, svhn
#  data_root: "/data0/user/kcli/Datasets"
  data_root: "/home/likunchi/Datasets"
  all_classes: 10
  all_tasks: 2
  split_seed: 0
  val_length: 0

# ----- extractor BUILDER -----
extractor:
#  TYPE: 'resnet18'
  #TYPE: "resnet34"
  TYPE: "res32_cifar"
  rate: 1.
  output_feature_dim: 64

#----- model -----
model:
  TRAIN:
    BATCH_SIZE: 128
#    MAX_EPOCH: 250
    MAX_EPOCH: 170
    NUM_WORKERS: 4
    SHUFFLE: True


#----- FCTM -----
FCTM:
  use_FCN: True
  FCN:
    in_feature_dim: 128
    out_feature_dim: 64
    layer_nums: 3
    hidden_layer_rate: 2
    last_hidden_layer_use_relu: True
  TRAIN:
    tradeoff_rate: 1.
    BATCH_SIZE: 128
    MAX_EPOCH: 170
    #MAX_EPOCH: 160
    NUM_WORKERS: 1
    SHUFFLE: True



